In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
dataset = pd.read_csv("C:/Users/user/Desktop/KAggle/Titanic/train.csv")

In [3]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
dataset=dataset.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)


In [5]:
dataset['Sex']=dataset['Sex'].map({'male':-1,'female':1})
dataset['Embarked']=dataset['Embarked'].map({'S':-1,'C':1,'Q':0})
dataset["Age"]=dataset["Age"].fillna(25)


In [6]:
dataset=dataset.fillna(0)

In [7]:
x1 = dataset.iloc[:,1:].values
y1 = dataset.iloc[:, 0].values

In [8]:
x1,y1

(array([[ 3.    , -1.    , 22.    , ...,  0.    ,  7.25  , -1.    ],
        [ 1.    ,  1.    , 38.    , ...,  0.    , 71.2833,  1.    ],
        [ 3.    ,  1.    , 26.    , ...,  0.    ,  7.925 , -1.    ],
        ...,
        [ 3.    ,  1.    , 25.    , ...,  2.    , 23.45  , -1.    ],
        [ 1.    , -1.    , 26.    , ...,  0.    , 30.    ,  1.    ],
        [ 3.    , -1.    , 32.    , ...,  0.    ,  7.75  ,  0.    ]]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1 = sc.fit_transform(x1)

In [10]:
x1

array([[ 0.82737724, -0.73769513, -0.5153082 , ..., -0.47367361,
        -0.50244517, -0.58871704],
       [-1.56610693,  1.35557354,  0.70334251, ..., -0.47367361,
         0.78684529,  1.93921974],
       [ 0.82737724,  1.35557354, -0.21064552, ..., -0.47367361,
        -0.48885426, -0.58871704],
       ...,
       [ 0.82737724,  1.35557354, -0.28681119, ...,  2.00893337,
        -0.17626324, -0.58871704],
       [-1.56610693, -0.73769513, -0.21064552, ..., -0.47367361,
        -0.04438104,  1.93921974],
       [ 0.82737724, -0.73769513,  0.2463485 , ..., -0.47367361,
        -0.49237783,  0.67525135]])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x1, y1, test_size = 0.10, random_state = 0)

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 4000, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=4000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[45  6]
 [11 28]]


In [15]:
testset = pd.read_csv("C:/Users/user/Desktop/KAggle/Titanic/test.csv")


In [16]:
testset=testset.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)


In [17]:
testset['Sex']=testset['Sex'].map({'male':-1,'female':1})
testset['Embarked']=testset['Embarked'].map({'S':-1,'C':1,'Q':0})
testset["Age"]=testset["Age"].fillna(25)

In [18]:
testset=testset.fillna(0)

In [19]:
testset

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0         3   -1  34.5      0      0    7.8292         0
1         3    1  47.0      1      0    7.0000        -1
2         2   -1  62.0      0      0    9.6875         0
3         3   -1  27.0      0      0    8.6625        -1
4         3    1  22.0      1      1   12.2875        -1
..      ...  ...   ...    ...    ...       ...       ...
413       3   -1  25.0      0      0    8.0500        -1
414       1    1  39.0      0      0  108.9000         1
415       3   -1  38.5      0      0    7.2500        -1
416       3   -1  25.0      0      0    8.0500        -1
417       3   -1  25.0      1      1   22.3583         1

[418 rows x 7 columns]

In [20]:
xtestset = testset.iloc[:,:].values

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtestset = sc.fit_transform(xtestset)

In [22]:
xtestset

array([[ 0.87348191, -0.75592895,  0.41507594, ..., -0.4002477 ,
        -0.49663711,  0.47091535],
       [ 0.87348191,  1.32287566,  1.39178018, ..., -0.4002477 ,
        -0.5114971 , -0.70076689],
       [-0.31581919, -0.75592895,  2.56382528, ..., -0.4002477 ,
        -0.46333473,  0.47091535],
       ...,
       [ 0.87348191, -0.75592895,  0.7276213 , ..., -0.4002477 ,
        -0.50701688, -0.70076689],
       [ 0.87348191, -0.75592895, -0.32721929, ..., -0.4002477 ,
        -0.49268018, -0.70076689],
       [ 0.87348191, -0.75592895, -0.32721929, ...,  0.61989583,
        -0.23626278,  1.64259759]])

In [23]:
ytestset = classifier.predict(xtestset)

In [24]:
ytestset

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [25]:
for i in ytestset:
    if(ytestset[i]>.3):
        ytestset[i]=1
    else:
        ytestset[i]=0

In [26]:
ytestset[ytestset>.3]=1

In [27]:
ytestset[ytestset<=.3]=0

In [28]:
ytestset

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [44]:
pd.DataFrame(ytestset).to_csv("C:/Users/user/Desktop/KAggle/Titanic/testrow3.csv")